gen_animal_terms = ["Aves",
                    "Bovinae",
                    "Canidae",
                    "Cetacea",
                    "Equidae",
                    "Felidae",
                    "Suidae",
                    "Procyonidae",
                    "Viverridae",
                    "Mustelidae",
                    "Leporidae",
                    "Osteichthyes"]

animal_species = ["Aardvark",
                  "Albatross",
                  "Alligator",
                  "Alpaca",
                  "Ant",
                  "Anteater",
                  "Antelope",
                  "Ape",
                  "Armadillo",
                  "Donkey",
                  "Baboon",
                  "Badger",
                  "Barracuda",
                  "Bat",
                  "Bear",
                  "Beaver",
                  "Bee",
                  "Beetle",
                  "Binturong",
                  "Bird",
                  "Wild boar",
                  "Bobcat",
                  "Budgerigar",
                  "Bubalina",
                  "Bull",
                  "Butterfly",
                  "Camel",
                  "Capybara",
                  "Cat",
                  "Cattle",
                  "Chamois",
                  "Herd",
                  "Cheetah",
                  "Chicken",
                  "Chimpanzee",
                  "Chinchilla",
                  "Coati",
                  "Cobra",
                  "Cockroach",
                  "Cod",
                  "Cormorant",
                  "Cow",
                  "Crab",
                  "Crane (bird)",
                  "Cricket (insect)",
                  "Crocodile",
                  "Crow",
                  "Curlew",
                  "Deer",
                  "Dinosaur",
                  "Dog",
                  "Puppy",
                  "Squalidae",
                  "Flake (fish)",
                  "Dolphin",
                  "Donkey",
                  "Dove",
                  "Dragonfly",
                  "Duck",
                  "Dugong",
                  "Dunlin",
                  "Eagle",
                  "Echidna",
                  "Eel",
                  "Elephant",
                  "Elephant seal",
                  "Elk",
                  "Emu",
                  "Falcon",
                  "Ferret",
                  "Finch",
                  "Fish",
                  "Flamingo",
                  "Fly",
                  "Fox",
                  "Frog",
                  "Gazelle",
                  "Gecko",
                  "Gerbil",
                  "Giant panda",
                  "Giraffe",
                  "Gnat",
                  "Wildebeest",
                  "Goat",
                  "Goose",
                  "Gorilla",
                  "Goshawk",
                  "Grasshopper",
                  "Grouse",
                  "Guanaco",
                  "Guinea fowl",
                  "Poultry",
                  "Guinea pig",
                  "Gull",
                  "Hamster",
                  "Hare",
                  "Hawk",
                  "Hedgehog",
                  "Hermit crab",
                  "Heron",
                  "Herring",
                  "Hippopotamus",
                  "Hornet",
                  "Horse",
                  "Hummingbird",
                  "Hyena",
                  "Ibex",
                  "Ibis",
                  "Iguana",
                  "Impala",
                  "Jaguar",
                  "Jay",
                  "Jellyfish",
                  "Planula",
                  "Jellyfish",
                  "Scyphozoa",
                  "Junglefowl",
                  "Kangaroo",
                  "Kingbird",
                  "Kinkajou",
                  "Kite (bird)",
                  "Koala",
                  "Komodo dragon",
                  "Ladybug",
                  "Lapwing",
                  "Lark",
                  "Lemur",
                  "Leopard",
                  "Lion",
                  "Lizard",
                  "Llama",
                  "Lobster",
                  "Loris",
                  "Louse",
                  "Lyrebird",
                  "Mammoth",
                  "Manatee",
                  "Mandrill",
                  "Manta ray",
                  "Mantis",
                  "Meerkat",
                  "Mink",
                  "Mole (animal)",
                  "Mongoose",
                  "Monkey",
                  "Moose",
                  "Mosquito",
                  "Mouse",
                  "Narwhal",
                  "Newt",
                  "Nightingale",
                  "Octopus",
                  "Okapi",
                  "Opossum",
                  "Ostrich",
                  "Otter",
                  "Ox",
                  "Owl",
                  "Oyster",
                  "Black panther",
                  "Parrot",
                  "Panda",
                  "Partridge",
                  "Peafowl",
                  "Pelican",
                  "Penguin",
                  "Pheasant",
                  "Domestic pig",
                  "Pigeon",
                  "Polar bear",
                  "Pony",
                  "Porcupine",
                  "Porpoise",
                  "Prairie dog",
                  "Pug",
                  "Quail",
                  "Rabbit",
                  "Raccoon",
                  "Sheep",
                  "Rat",
                  "Raven",
                  "Red deer",
                  "Red panda",
                  "Rhinoceros",
                  "Rook (bird)",
                  "Salamander",
                  "Salmon",
                  "Sand dollar",
                  "Sandpiper",
                  "Sardine",
                  "Sea lion",
                  "Seahorse",
                  "Pinniped",
                  "Sea otter",
                  "Shark",
                  "Flake (fish)",
                  "Sheep",
                  "Shrew",
                  "Skink",
                  "Skipper (butterfly)",
                  "Skunk",
                  "Sloth",
                  "Snail",
                  "Snake",
                  "Spider",
                  "Spoonbill",
                  "Squid",
                  "Squirrel",
                  "Starfish",
                  "Bipinnaria",
                  "Starling",
                  "Stilt",
                  "Stingray",
                  "Swan",
                  "Tapir",
                  "Tarsier",
                  "Termite",
                  "Thrush (bird)",
                  "Tiger",
                  "Toad",
                  "Toucan",
                  "Turkey",
                  "Turtle",
                  "Viper",
                  "Wallaby",
                  "Walrus",
                  "Wasp",
                  "Weasel",
                  "Whale",
                  "Wildebeest",
                  "Wolf",
                  "Wolverine",
                  "Wombat",
                  "Zebra"]
