shot_type_list = [
    "close-up shot",
    "medium shot",
    "long shot",
    "close up shot",
    "extreme close up shot",
    "extreme long shot",
    "chest shot",
    "over the shoulder shot",
    "pov shot",
    "establishing shot",
    "low angle shot",
    "ground level shot",
    "knee level shot",
    "hip level shot",
    "eye level shot",
    "high angle shot",
    "bird's eye view shot",
    "aerial shot",
    "dutch camera angle shot",
]

lens_type = [
    "telephoto",
    "wide angle",
    "portrait",
    "prime",
    "zoom",
    "mid length"
]

painting_type = [
    "Pencil Sketch",
    "Oil Painting",
    "Watercolor Painting",
    "Charcoal Drawing",
    "Mixed media painting",
    "Pencil Color Drawing",
    "Collage Painting",
    "Kalamkari Painting",
    "Scribble Art",
    "Nib Painting",
    "Ink-wash Painting ",
    "Acrylic Painting ",
    "Pastel Painting",
    "Glass Painting",
    "Fresco Painting",
    "Encaustic Painting",
    "Gouache Painting",
    "Splash Painting",
    "Sand Painting",
    "Spray painting  ",
    "Board Painting ",
    "Scroll Painting ",
    "Pulling and Scrapping",
    "Body Painting",
    "Impasto Technique",
    "Casein Painting ",
    "Warli Painting",
    "Pahad Painting",
    "Madhubani Painting",
    "Gond Paintings",
    "Patachitra Paintings",
    "Picchwai Painting",
    "Mughal Paintings",
    "Cavern Paintings",
    "Texture Painting",
    "Modernism",
    "Impressionism",
    "Expressionism",
    "Cubism",
    "Surrealism",
    "Chinese Painting",
    "The Japanese Painting",
    "Rajput Painting",
    "Mysore Painting",
    "Tanjore Painting",
    "Tenebrism Painting",
    "Display Painting",
    "Viewpoint Painting",
    "Consolidate Paintings",
    "Foreshortening",
    "Sfumato",
    "Sgraffito"
]
